### ISSUE TITLE
API接口文档

### ISSUE THREAD

**Issue by victory460** [bfenetworks/api-server#17]
用于下发配置的api文档在哪里哇？

**Comment by liuqing6767** [comment]
配置下发相关的API的是内部服务才会调用的API，当前并没有提供接口文档。

请问是什么场景需要这个文档呢？我们进一步评估是否需要提供。

**Comment by victory460** [comment]
> 配置下发相关的API的是内部服务才会调用的API，当前并没有提供接口文档。
> 
> 请问是什么场景需要这个文档呢？我们进一步评估是否需要提供。

感谢您的回复。
场景：比如不想通过修改文件进行配置route、upstream等，想通过api去热更新配置。 
顺便请教下，通过api热更新后，能够持久化配置吗？比如更新到配置文件中去。

**Comment by liuqing6767** [comment]
控制面的一大功能是通过OpenAPI更新配置后，触发BFE实例热更新。
具体完成这个功能的是[conf-agent模块](https://github.com/bfenetworks/conf-agent) 。

配置最终是会持久化的，conf-agent步骤简要说明 见 [conf-agent 实现简单说明](https://github.com/bfenetworks/conf-agent/blob/develop/docs/zh_cn/implementation.md) 。

**Comment by victory460** [comment]
针对通过api去热更新配置（route、upstream等）的场景；这些API暂时还未开放 对吧？后期考虑开放吗？
