### ISSUE TITLE
db_ddl.sql初始化mysql 5.7.0错误

### ISSUE THREAD

**Issue by coder-user** [bfenetworks/api-server#3]
ERROR 1067 (42000) at line 195: Invalid default value for 'session_key_created_at'

**Comment by liuqing6767** [comment]
mysql 有个 NO_ZERO_DATE 的限制，你可以先去掉就可以创建成功了。

后期我们更新一下建表语句完成这个兼容。

**Comment by liuqing6767** [comment]
默认值已经修改为 "0000-01-01 00:00:00"
